name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release --base-href "/ali_portfolio/"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'
      - uses: actions/deploy-pages@v4
